### ISSUE TITLE
[question] generate customization

### ISSUE THREAD

**Issue by Freed-Wu** [heavenshell/py-doq#121]
By default, doq will generate

```python
def get_parser():
    """get_parser."""
```

How can I get

```python
def get_parser():
    """Get Parser."""
```
?

TIA!

**Comment by heavenshell** [comment]
@Freed-Wu Sorry for late response.

You can use Jinja2 template's method.

```jinja2
"""{{ name.replace('_', ' ').capitalize() }}."""
```

See https://jinja.palletsprojects.com/en/3.1.x/templates/#python-methods details

**Comment by Freed-Wu** [comment]
Thanks!
The trouble is for `get_parser`, `replace("_", " ")` is enough. for `getParser`, I need `replace("A", " a").replace("B", " b"). ... .replace("Z", " z")`. Is there any good method to handle camlecase?
