### ISSUE TITLE
[feature] Shell completion

### ISSUE THREAD

**Issue by Freed-Wu** [heavenshell/py-doq#124]
Can it provide completions for common shells? Like <https://docs.iterative.ai/shtab>. TIA!

**Comment by heavenshell** [comment]
merged. Thank you so much!
https://github.com/heavenshell/py-doq/pull/125

**Comment by Freed-Wu** [comment]
You are welcome. Can you publish 0.9.2?

**Comment by heavenshell** [comment]
Yep, will release it within a few days.
