### ISSUE TITLE
When there a function already has a docstring, tool emits nothing.

### ISSUE THREAD

**Issue by Icantjuddle** [heavenshell/py-doq#138]
A common method of editor integration is to pass some subset of text to a tools' stdin and replace it with the tool's stdout. This is common for formatters, linters, generators, etc.

In this case, piping a function to `doq` that already has a docstring causes no text to be emitted thereby deleting the code we want to add/update the docstring on.

It would be great if `doq` could either:
1. pass through the text unchanged.
2. replace the docstring with a new one.

Example

```
$ echo "def myfunc():\n    pass" | doq
def myfunc():
    """myfunc."""
    pass
$
```

vs 

```
$ echo "def myfunc()\n    '''docstring'''\n    pass" | doq
$
```

**Comment by heavenshell** [comment]
@Icantjuddle Sorry for late response.
Current behavior is `1.`.

```
cat sample2.py
def foo(foo, bar):
    """foo.

    :param arg1:
    :param arg2:
    """
    pass


def bar(arg1, arg2):
    pass
```
def foo has docstring already, then run doq command.
```
cat sample2.py | lib/doq
def foo(foo, bar):
    """foo.

    :param arg1:
    :param arg2:
    """
    pass


def bar(arg1, arg2):
    """bar.

    :param arg1:
    :param arg2:
    """
    pass
```

Introducing `override` is in my todo list.
Sorry it's taking so long, but please wait patiently.
