### ISSUE TITLE
`google` styles should not include types

### ISSUE THREAD

**Issue by nexushoratio** [heavenshell/py-doq#143]
From https://google.github.io/styleguide/pyguide.html#doc-function-args (emphasis mine):
> The description should include required type(s) **if** the code does **not** contain a corresponding type annotation.

And the next paragraph about Returns/Yields:
> Describe the semantics of the return value, including any type information that the type annotation does **not** provide.

It looks like that has been the text (or close to it), since the public version migrated from HTML to MD with https://github.com/google/styleguide/commit/54cca78

**Comment by heavenshell** [comment]
@nexushoratio
Thank you for letting me know.
I used sphinx as a reference.
https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#google-vs-numpy

Anyway, we can use `--template_path` to change your custom docstring.
Should I change the default template?
If we change it, it will cause a BCBreak, which is not very desirable 😰

**Comment by nexushoratio** [comment]
That sphinx example is also wrong on where the type is and how it should be formatted.  It should be somewhere after the `:`, but where exactly and how is unspecified.  In most code I was researching while filing this bug, it would just be mentioned in the.  For example,
```
arg1: The integer arg1 does description.
```
Personally, I always used a comma:
```
arg1: int, Description of arg1.
```
and no one complained during my reviews.

With annotations wide spread now, I imagine it would be hard to find current public Google code that demonstrates any types in the docstrings.  But I would be very surprised to find any old code that ever matched that sphinx example.  At least, I certainly don't remember ever seeing anything like that during my tenure there.


I'm not sure why you would consider it a breaking change.  I didn't see any project notes stating you guarantee bit-by-bit compatibility between releases.

You could do a transition between "broken" and "fixed" by creating a new template called "google2" and copy the existing in to "google1" so folks would have a choice between "google", "google1", "google2" with "google" and "google1" being the same (for now), giving users time to make a decision.  Then some time in the future, make "google" equivalent to "google2" (or just retiring "google", if you don't want to bother supporting aliases or keeping duplicate files around).

Also, I would actually suggest putting a dummy type placeholder for those that do not have types.  To take the example off your README:
```
  Args:
      arg1: (UNKNOWN_TYPE) arg1
      arg2: arg2
```

Just to make the users fill it in.  Obviously, a better string than "UNKNOWN_TYPE", but as I've never used sphinx, I don't know if they have a generic placeholder or not.

**Comment by heavenshell** [comment]
Use `--template_path`.
It is the author who complains that backward compatibility is broken.
