### ISSUE TITLE
More elements from parso

### ISSUE THREAD

**Issue by AleCandido** [heavenshell/py-doq#29]
I noticed that in order to get the elements of the definition this package is using `parso` under the hood.

Since `parso` is exposing more elements should be not so difficult to make them available for template. In particular:
- *functions*: there are also `yield` statements available on top of what is already implemented
- *module*: there is some content available for modules, like *used_names*, that can be used for implementing a module template to be added to the existing ones

P.S.: to be honest I'm still struggling with exceptions, since nor the default, nor numpy neither a custom theme is able to catch them, but I will document this in a separate issue if they keep not to work

**Comment by heavenshell** [comment]
Could you show me sample code?
and expected result?

**Comment by AleCandido** [comment]
Yes, for example:
``` python

def example_generator(n):
    """Generators have a ``Yields`` section instead of a ``Returns`` section.

    Parameters
    ----------
    n : int
        The upper limit of the range to generate, from 0 to `n` - 1.

    Yields
    ------
    int
        The next number in the range of 0 to `n` - 1.

    """
    for i in range(n):
        yield i
```
taken from [sphinx-docs](https://www.sphinx-doc.org/en/1.8/usage/extensions/example_numpy.html).

**Comment by AleCandido** [comment]
Maybe it's not enough explicit: so if `yield` is detected provide a `Yields` section in place of `Returns`, but delivering the detected `yields` as a separate object to allow templating them differently.

**Comment by heavenshell** [comment]
Thx for show me example.
I don't know parso can handle `yield`.
So, I will look into it.

If parso can handle yeild, I think I will implement same as `exception`.
(add something like --ignore_yeild option)

**Comment by AleCandido** [comment]
> If parso can handle yeild, I think I will implement same as exception.

I told you because I've already checked :wink::
- [yield](https://parso.readthedocs.io/en/latest/docs/parser-tree.html#parso.python.tree.Function.iter_yield_exprs)
- [module](https://parso.readthedocs.io/en/latest/docs/parser-tree.html#parso.python.tree.Module.get_used_names)

**Comment by heavenshell** [comment]
Thx

> yield

What should we generate?

```python
    for number in range(n):
        yield number
```

parso can't get `type`.

```
Yields
------
number
  
```

Is this ok?

**Comment by heavenshell** [comment]
> modules

I think it's too much.

e.g
```
"""

Attributes
----------
    module_level_var
"""

# long
# long
# long
# source code above module var

module_level_var = 'foobar'
```


```
# inline comment
module_level_var = 'foobar'
```

IMO about module(variable) docstring, I prefer inline docstring.

- docstring may generated near definition `class | function | variable`
- parsing all module level variable is too expensive i think
- I think `add | edit | delete` variable by user happen many time
- Once generate top-level docstring, never update even if delete docstring(You already knew 😉 )

Yield: yes, let's implement
module level variable: Sorry no, I don't implement

**Comment by AleCandido** [comment]
> parso can't get `type`.
> 
> ```
> Yields
> ------
> number
>   
> ```
> 
> Is this ok?

I think that is perfect, the only improvement may be that the type if available should be taken from function annotation, exactly the same as the `Return` paragraph.

> IMO about module(variable) docstring, I prefer inline docstring.
> [...]
> - parsing all module level variable is too expensive i think

It's fine, and probably as you said it is better not to use *global* docstring as you said (even if sometimes is good to document module variables if you are going to use them publicly), my suggestion was:
1. coming from the availability of them in `parso`
2. to make them available for custom templates, but not to include them in the default one and of course not to run them if not required

However I'm pretty happy like this, I was not going to use anything else, indeed for collecting global stuffs `sphinx.autodoc` is already doing the job without the need of writing anything in the docstrings, so it would be also redundant in this respect.

Thank you for everything :smiley:

**Comment by heavenshell** [comment]
Thx for comment!
I released, so please try 😊

**Comment by AleCandido** [comment]
I'm sorry but sadly nor this neither `exceptions` is working for me (`doq` version: 0.6.0).

Can you give me an example that is working for you (maybe with both `exceptions` and `yields`) and the invocation string for `doq` from `shell`?

**Comment by heavenshell** [comment]
@AleCandido 

```console
$ cat sample.py 
def example_generator(n):
    # foo
    # bar
    for i in range(n):
        yield i
```

```
$ cat sample.py | python -m doq.cli --template_path=./examples                                  
def example_generator(n):
    """Summary of example_generator.

    Args:
        n

    Yields:
        i:
    """
    # foo
    # bar
    for i in range(n):
        yield i
```

**Comment by AleCandido** [comment]
I made some experiments:

1. I am able to reproduce your example :heavy_check_mark: 
2. It is working fine also with exceptions :heavy_check_mark:
3. If I add any annotation to your example it is not producing any output :negative_squared_cross_mark: 
  - annotation are broken in general (both with the example template and the default one), mwe:
```python
def spam(arg1, arg2: str) -> str:
    pass
```
4. from `pydocstring` I have a different behavior :negative_squared_cross_mark:
  - `yield` ignored
  - annotations working perfectly

I tried with some test chosen without a strategy, because I don't know exactly what should I search for, if you have any idea tell me what to test and I will do it.

**Comment by heavenshell** [comment]
@AleCandido 
Works fine for me.
![Kapture 2020-04-10 at 19 43 43](https://user-images.githubusercontent.com/56591/78985415-b2cd5000-7b63-11ea-917a-de191b6e0092.gif)

- If you want generate, yield, exception to docstring, you have to use visual select or `:PydocstingFormat`
- Built-in template does not contain yields keyword, so you have to create your own custom template
  - Yield sample template are in `doq/examples`
- I'll update vim-pydocstring's document this weekend

**Comment by AleCandido** [comment]
I already have my custom template, and indeed you are right: it is working if I select the function before, while before I was simply placing my cursor on the line of the definition and then calling Pydocstring.

I don't know why I was/am not able to use properly `doq`, but since it is working in `pydocstring` honestly I don't care so much. But if you need some more examples I can still provide them.

**Comment by heavenshell** [comment]
@AleCandido 
🎉 
I know both `doq` and `vim-pydocstring` is less document.
Documentation PRs are very very welcome and it's very important OSS contribution 😉 
(You know, my English is not good)

**Comment by AleCandido** [comment]
Perfect. I admit that it's not a priority to write the docs for this project, but since it is a useful plugin for me and I had a look inside I will consider to do it :wink: 

Thank you for everything :bow:
