### ISSUE TITLE
Multi-line return annotations

### ISSUE THREAD

**Issue by brentyi** [heavenshell/py-doq#51]
Hi,

Thanks for the super useful tool! Just wanted to report one minor/non-urgent issue that I've been running into recently --

Specifically, running `doq` on:
```python
from typing import Tuple


def x(a, b, c) -> Tuple[
    int,
    int,
    int,
]:
    pass
```

produces:
```python
from typing import Tuple


def x(a, b, c) -> Tuple[
    """x.

    :param a:
    :param b:
    :param c:
    """
    int,
    int,
    int,
]:
    pass
```

Seems like two issues:
- `detect_insert_point()` breaks in outputter.py
- `parse_return_type()` breaks in parser.py; note that there are no return annotations above

For the latter: I think `parse_return_type()` could be replaced by checking the parso tree, for example in `parse_defs()`:
```python
        if d.children[3].value == "->":
            # Get return-type annotation
            return_type = d.children[4].get_code().strip() 
        else:
            # No annotation
            return_type = None
```
(child indices are from [here](https://github.com/davidhalter/parso/blob/034a9e89443261e7f434fcb1fbb807b14991b766/parso/python/tree.py#L536))

Some thought may also need to be put into how indents, etc are handled?

@heavenshell if you don't have time to fix, I might spontaneously submit a PR sometime next month. :slightly_smiling_face:

**Comment by heavenshell** [comment]
@brentyi Thank you for report!
Nice catch! I did't realize this.
I'll look into this issue in next few days, but bit busy now, so please stay tuned 😉 

>For the latter: I think parse_return_type() could be replaced by checking the parso tree, for example in parse_defs():

Great! thx I also look into it.

P.S.
Fixing issue, tests, docs(you know my English is poor 😉 ) etc are very very welcome!

**Comment by heavenshell** [comment]
@brentyi 
Fixed and release as 0.6.4
![Kapture 2020-11-21 at 22 51 46](https://user-images.githubusercontent.com/56591/99878939-3f88d200-2c4c-11eb-859f-114e1d16508f.gif)

Currentlry output like following.
```
from typing import Tuple


def x(a, b, c) -> Tuple[
    int,
    int,
    int,
]:
    """x.

    :param a:
    :param b:
    :param c:
    :rtype: Tuple[
        int,
        int,
        int,
    ]
    """
    pass
```

Do you have any idea about rtype should be one-line or multi-line?
multi-line(current output)
```
    :rtype: Tuple[
        int,
        int,
        int,
    ]
```
or one-line
```
    :rtype: Tuple[int, int, int,]
```

**Comment by brentyi** [comment]
Thanks @heavenshell!!

Assuming it's compatible with the docstring standards, I think multi-line is better. Breaking up an annotation into multiple lines is most common when the annotation itself is very long --- if the arglist was long we would just break up the arglist --- so this would usually be more readable.

**Comment by heavenshell** [comment]
@brentyi Thx!
Ok, output would be multi-line 😊
