### ISSUE TITLE
Not available on some conda package index

### ISSUE THREAD

**Issue by benjamin9555** [heavenshell/py-doq#62]
`py-doq` in combination with `vim-pydocstring` is great, thanks for creating them. It would be useful to install it it by default in conda environments via `.condarc`. May I suggest a [release to conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html#dev-contribute-pkgs), this might be a fairly easy way to make this possible.

**Comment by heavenshell** [comment]
@benjamin9555 
Sorry for late response and thank you for suggestion!
I'm not conda user and I don't want manage/maintain conda repo.

If you can maintain feedstock,  you can add doq to conda-forge ☺️ 
doq's license(https://github.com/heavenshell/py-doq/blob/master/LICENSE) is here.
cheers!
