### ISSUE TITLE
* not included for *args & **kwargs

### ISSUE THREAD

**Issue by khaveesh** [heavenshell/py-doq#67]
Take the following function as an example:
```
def fun(x, *args, **kwargs):
    pass
```

Passing this to doq produces the following:
```
def fun(x, *args, **kwargs):
    """fun.

    :param x:
    :param args:
    :param kwargs:
    """
    pass
```

As you can see, doq gobbles the * from the arguments.

Another issue is that doq strips the trailing newline at the end of the file which is undesirable for obvious reasons.

**Comment by heavenshell** [comment]
@khaveesh 
Thank you for reporting.

Yes, this is by design.
If you want add `*` to docstring, you can modify template.

e.g.
Edit def.txt.
```jinja
"""{{ name }}.

{% for p in params -%}
:param {% if p.argument == 'args' %}*{% elif p.argument == 'kwargs' %}**{% endif %}{{ p.argument }}:
{% if p.annotation -%}
:type {{ p.argument }}: {{ p.annotation }}
{% endif -%}
{% endfor -%}
{% if return_type -%}
:rtype: {{ return_type }}
{% endif -%}
"""
```

```console
$ cat sample.py | python -m doq.cli
def foo(arg1, *, foo=None, **kwargs):
    """foo.

    :param arg1:
    :param foo:
    :param **kwargs:
    """
    pass
```

> Another issue

Please create another issue and write more detail?
(steps to reproduce etc).

**Comment by khaveesh** [comment]
The snippet works perfectly. Maybe include it in a FAQ section?
