### ISSUE TITLE
EOF newline is stripped off

### ISSUE THREAD

**Issue by khaveesh** [heavenshell/py-doq#68]
Take the following file as an example:
```
# file.py
def f(x):
    pass

```
Notice the last empty line which is *required* by git to diff files properly.

Now, passing this file to doq using this command: `doq -w -f file.py`, produces the following:
```
# file.py
def f(x):
    """f.

    :param x:
    """
    pass
```
Notice that the last line has been stripped

**Comment by heavenshell** [comment]
Thank you!
I'll investigate this.

**Comment by heavenshell** [comment]
Release 0.7.0
https://pypi.org/project/doq/0.7.0/

**Comment by khaveesh** [comment]
It fixes the issue. Thank you
