### ISSUE TITLE
Include 'return' in the docstring if the function returns anything

### ISSUE THREAD

**Issue by khaveesh** [heavenshell/py-doq#69]
Take the following function as an example:
```
def f(x):
    return x
```
Passing this to doq produces:
```
def f(x):
    """f.

    :param x:
    """
    return x
```

It can be seen that doq does not include the 'returns' part in the docstring despite the function returning an expression.
But in the case of an `yield` statement, doq does include it in the docstring given that the template is modified appropriately. I propose to make return to behave in a similar fashion.

**Comment by khaveesh** [comment]
Doq uses parso's `iter_yield_exprs()` to check if the function yields any expression. Similarly, parso also has the `iter_return_stmts()` function which I believe can be used to implement this feature request.

**Comment by heavenshell** [comment]
Fmm, I understand your request.
But I don't like list returns to docstring.

```python
def foo(arg):
  """foo
  :param: arg
  :return: foo
  :return: bar
  :return: ...
  """
  if arg == 'a':
    return 'foo'
  elif arg == 'b':
    return 'bar'
  ...
```

IMO, you may use return type instead of listing returns.

```python
from typing import Any


def foo(arg) -> Any:
    """foo.

    :param arg:
    :rtype: Any
    """
    return arg
```

**Comment by khaveesh** [comment]
Understood, I'll close the issue. Thanks for the response
