### ISSUE TITLE
methods with multi-line arguments

### ISSUE THREAD

**Issue by njzjz** [heavenshell/py-doq#82]
Similar of #51, but here the multi-line arguments cannot be processed.

![image](https://user-images.githubusercontent.com/9496702/130314277-8ec308a0-3ac7-46d7-8a43-b4d3cfeb95b9.png)

**Comment by heavenshell** [comment]
Thx for reporting. I'll investigate this.

**Comment by heavenshell** [comment]
Released as 0.8.0
https://pypi.org/project/doq/0.8.0
