### ISSUE TITLE
[feature] Update docstring

### ISSUE THREAD

**Issue by Freed-Wu** [heavenshell/py-doq#89]
<https://github.com/yaegassy/coc-pydocstring/issues/11>

Thanks!

**Comment by yaegassy** [comment]
@Freed-Wu Please check this issue.

- <https://github.com/heavenshell/py-doq/issues/30>
- <https://github.com/heavenshell/vim-pydocstring/issues/107>

**Comment by Freed-Wu** [comment]
I see, this issue is repeated. Let us close it.
